### ISSUE TITLE
Global search bug

### ISSUE THREAD

**Issue by akshat24sharma** [CoderSau/react-flexy-table#10]
Hey, I think there is a bug in global search, if you're on any page other than the 1st one you will get zero records on that page when filtered, you have to trigger an event either by changing rows or by changing the page number from text column then only it'll come back to the page 1, can you fix that?

 thank you

**Comment by CoderSau** [comment]
Hi akshat24sharma, thank you for feedback.

problem solved at version 1.7.0. Now when you search something table will change the page number to 1.

**Comment by akshat24sharma** [comment]
Thank you!!
