### ISSUE TITLE
global search for table

### ISSUE THREAD

**Issue by soql101** [CoderSau/react-flexy-table#2]
Instead of search boxes for all column for table how we can add single global search for column?

**Comment by CoderSau** [comment]
fow now there is no way to do that. Maybe I can add something like that so you can use it.

**Comment by soql101** [comment]
that would be really helpful

**Comment by CoderSau** [comment]
Hi,

I've add a new feature for global search. 

You can use like that 

`
<ReactFlexyTable data={data}  globalSearch/>
`

for more information you can check the readme file.

live demo:

https://react-flexy-table.netlify.app/
