### ISSUE TITLE
add image

### ISSUE THREAD

**Issue by premu21** [CoderSau/react-flexy-table#5]
How to add an image to a cell in the table??
Also how to append the additional columns in starting of the table rather than at the end?

**Comment by CoderSau** [comment]
hi I add a new feature about it in version 1.3.5

you can spesify your columns with columns property 

`
import ReactFlexyTable from 'react-flexy-table'
import 'react-flexy-table/dist/index.css'

const App = () => {
  columns = [
    {
      header: 'id value',
      key: 'id',
      td: (data) => <div>the id is {data.id}</div>
    },
    {
      header: 'username',
      key: 'name'
    }
  ]
  return <ReactFlexyTable data={data} columns={columns} />
}
export default App
`
with using this you can change the rendered value in table like additionalCol .and also add your additional columns whereever you like.
