### ISSUE TITLE
How to remove unnecessary column from the table (e.g. Created At,  Updated At)

### ISSUE THREAD

**Issue by nazmulweb** [CoderSau/react-flexy-table#6]
Hi,
I am using react-flexy-table in my project. it's working well. but I want to remove some columns from the table (e.g. Created At,  Updated At). they are coming from API. is there any way to remove them?

Thank you

**Comment by CoderSau** [comment]
hi,
with columns property you can specify the columns on the table. 

Here is an example:

```js
import ReactFlexyTable from 'react-flexy-table'
import 'react-flexy-table/dist/index.css'

const App = () => {
  columns = [
    {
      header: 'id value',
      key: 'id',
      td: (data) => <div>the id is {data.id}</div>
    },
    {
      header: 'Username',
      key: 'name'
    }
  ]
  return <ReactFlexyTable data={data} columns={columns} />
}
```

**Comment by nazmulweb** [comment]
Hi,
The above example code is not working for me. I am using like this:
` if (data !== undefined) {
        const columns = [
            {
                header: 'Id',
                key: 'id',
                td: (data) => <div>the id is {data.id}</div>
            },
            {
                header: 'Title',
                key: 'title'
            },
            {
                header: 'Image',
                key: 'image'
            },

            {
                header: 'Status',
                key: 'status'
            },
        ]
        return <ReactFlexyTable data={data} columns={columns} sortable globalSearch />
    } else {
        return <div>loading.....</div>
    }
}`

**Comment by CoderSau** [comment]
can you share the error code too?
