### ISSUE TITLE
Is that possible to add a new row to the table?

### ISSUE THREAD

**Issue by RuiRitaYang** [CoderSau/react-flexy-table#7]
Hi group,

Thanks for this fantastic lib. I'm wondering whether it's possible to add a new row to the table in this lib?

Thanks,
-Rui

**Comment by giupo** [comment]
@RuiRitaYang I've no relation with the author, but I think your request can be resolved fast: can't you just add a "row" to the data array then by changing the state of the component you'll issue a new rendering of  `<ReactFlexyTable />` ?

just my 2 cents here ;)

**Comment by CoderSau** [comment]
hi RuiRitaYang

you have to way to add a new columns.

1)

You can type additional columns with additionalCol props 
like this

```js
 const additionalCols = [
    {
      header: 'Actions',
      td: (data) => {
        return (
          <div>
            <img
              width='30'
              height='20'
              onClick={() => alert('this is delete for id ' + data.id)}
            />{' '}
            // delete icon
            <img
 
              width='30'
              height='20'
              onClick={() => alert('this is edit for id ' + data.id)}
            /> // edit icon
          </div>
        )
      }
    }
  ]
  return <ReactFlexyTable data={data} additionalCols={additionalCols} />
````

td value represent the value in row. You can return  a jsx.
header value represent the value in the header row.


2)

you can also define your columns so you can change the table values anything you like. (Note if you define columns your additionalcol value will not work)

```js
 columns = [
    {
      header: 'id value',
      key: 'id',
      td: (data) => <div>the id is {data.id}</div>
    },
    {
      header: 'username',
      key: 'name'
    },
    {
      header: 'city',
      // can also use with nested objects
      key: 'address.city'
    }
  ]
  return <ReactFlexyTable data={data} columns={columns} />
```

**Comment by RuiRitaYang** [comment]
> @RuiRitaYang I've no relation with the author, but I think your request can be resolved fast: can't you just add a "row" to the data array then by changing the state of the component you'll issue a new rendering of `<ReactFlexyTable />` ?
> 
> just my 2 cents here ;)

Thanks a lot! I think I miss the "issue a new rendering" part so I didn't successfully update the info. Too new to web development. Thanks a lot!

**Comment by RuiRitaYang** [comment]
> hi RuiRitaYang
> 
> you have two way to add a new columns.
> 
> 
> You can type additional columns with additionalCol props
> like this
> 
> ```js
>  const additionalCols = [
>     {
>       header: 'Actions',
>       td: (data) => {
>         return (
>           <div>
>             <img
>               width='30'
>               height='20'
>               onClick={() => alert('this is delete for id ' + data.id)}
>             />{' '}
>             // delete icon
>             <img
>  
>               width='30'
>               height='20'
>               onClick={() => alert('this is edit for id ' + data.id)}
>             /> // edit icon
>           </div>
>         )
>       }
>     }
>   ]
>   return <ReactFlexyTable data={data} additionalCols={additionalCols} />
> ```
> 
> td value represent the value in row. You can return a jsx.
> header value represent the value in the header row.
> 
> 
> you can also define your columns so you can change the table values anything you like. (Note if you define columns your additionalcol value will not work)
> 
> ```js
>  columns = [
>     {
>       header: 'id value',
>       key: 'id',
>       td: (data) => <div>the id is {data.id}</div>
>     },
>     {
>       header: 'username',
>       key: 'name'
>     },
>     {
>       header: 'city',
>       // can also use with nested objects
>       key: 'address.city'
>     }
>   ]
>   return <ReactFlexyTable data={data} columns={columns} />
> ```

Hi CoderSau, 

Thanks for the detail reply. Your suggestion seem to focus on adding columns instead of rows, but they definitely help a lot. Thanks!
